### ISSUE TITLE
Create a summary to clarify the different kinds of tokens

### ISSUE THREAD

**Issue by merlinND** [AnyFetch/developers.anyfetch.com#12]
After reading the first few paragraphs of the Hello World guide, I already came across three different kinds of tokens:
- OAuth
- FetchAPI specific authentication token
- Document-specific token (retrieved after [sending a document](https://github.com/Papiel/developers.anyfetch.com/blob/gh-pages/guides/hello-world.md#send-a-document))

It would be great to have a one-stop page to clarify exactly the purpose and usage of each kind of token.

**Comment by Neamar** [comment]
The first and second one are the same.

But you're right we ought to clarify this somewhere.
